(()=>{
'use strict';
const ASSET='資産運用';
const LEGACY='../lifeplan-calculator/?embedded=asset&v=6';
const DETAIL=['配偶者控除','扶養親族','住宅ローン控除額','iDeCo掛金','ふるさと納税額','社会保険料率'];
let overlay=null,frame=null,activeButton=null;
const norm=v=>(v||'').replace(/[\s\u00a0]+/g,'').trim();
const own=e=>norm([...e.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join(''));
const visible=e=>{if(!e)return false;const s=e.ownerDocument.defaultView.getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
const common=els=>{let a=els[0];while(a&&!els.every(e=>a.contains(e)))a=a.parentElement;return a};
function exactAll(root,label){const n=norm(label);return [...root.querySelectorAll('label,span,p,div')].filter(e=>!e.closest('#lc-bars')&&(own(e)===n||norm(e.textContent)===n)).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)}
const exact=(root,label)=>exactAll(root,label)[0]||null;
function wrapperFrom(root,el,withRange=false){let n=el;while(n&&n!==root.body){const controls=[...n.querySelectorAll('input,select')].filter(c=>withRange||c.type!=='range');if((withRange&&controls.some(c=>c.type==='range')&&controls.some(c=>c.type!=='range'))||(!withRange&&controls.length===1))return n;n=n.parentElement}return null}
function field(root,label,withRange=false){const el=exact(root,label);return el?wrapperFrom(root,el,withRange):null}
function addMainCss(){if(document.getElementById('lc-main-v6'))return;const s=document.createElement('style');s.id='lc-main-v6';s.textContent=`
.lc-detail-panel{display:grid!important;grid-template-columns:1fr!important;gap:10px!important;padding:14px!important;border:1px solid #d7e2ef!important;border-radius:14px!important;background:#f7faff!important}
.lc-detail-row{grid-column:1/-1!important;display:grid!important;grid-template-columns:minmax(145px,.8fr) minmax(190px,1.2fr)!important;align-items:center!important;gap:14px!important;padding:10px 12px!important;border:1px solid #e1eaf4!important;border-radius:12px!important;background:#fff!important;min-width:0!important}
.lc-detail-row input,.lc-detail-row select{width:100%!important;min-width:0!important;height:46px!important;box-sizing:border-box!important;border:1px solid #cbd8e8!important;border-radius:10px!important;background:#fff!important;color:#0a2247!important;font-size:16px!important;font-weight:700!important}
.lc-detail-row input:focus,.lc-detail-row select:focus{outline:3px solid rgba(47,124,229,.16)!important;border-color:#2f7ce5!important}
@media(max-width:760px){.lc-detail-panel{padding:10px!important}.lc-detail-row{grid-template-columns:1fr!important;gap:7px!important;padding:11px!important}}
`;document.head.appendChild(s)}
function improveDetails(){const rows=[];DETAIL.forEach(label=>exactAll(document,label).forEach(el=>{const row=wrapperFrom(document,el,false);if(row&&!rows.includes(row))rows.push(row)}));if(rows.length<4)return;const panels=new Set;rows.forEach(row=>{let n=row.parentElement;while(n&&n!==document.body){const labels=DETAIL.filter(label=>norm(n.textContent).includes(norm(label))).length,controls=n.querySelectorAll('input,select').length;if(labels>=4&&controls<=12){panels.add(n);break}n=n.parentElement}});panels.forEach(panel=>{panel.classList.add('lc-detail-panel');rows.filter(row=>panel.contains(row)).forEach(row=>{row.classList.add('lc-detail-row');row.style.gridColumn='1 / -1';row.querySelectorAll('input,select').forEach(c=>{c.autocomplete='off';if(c.tagName==='INPUT'&&c.type!=='range')c.inputMode='decimal'})})})}
function closeOverlay(){if(overlay)overlay.style.display='none';activeButton=null}
function positionOverlay(){if(!overlay||!activeButton)return;const r=activeButton.getBoundingClientRect();overlay.style.top=Math.max(108,Math.ceil(r.bottom+10))+'px'}
function assetCss(doc){if(doc.getElementById('lc-asset-v6'))return;const s=doc.createElement('style');s.id='lc-asset-v6';s.textContent=`
html{background:#fff!important}body{font-family:system-ui,-apple-system,"Segoe UI","Noto Sans JP",sans-serif!important;background:#fff!important;color:#0a2247!important}header,footer{display:none!important}main{max-width:1180px!important;padding:18px 22px 48px!important;margin:0 auto!important}.no-print{display:none!important}button,input,select{font-family:inherit!important}
.lc-tabs{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important;margin:2px 0 22px!important}.lc-tab{min-height:62px!important;border:1px solid #d8e3ef!important;border-radius:12px!important;background:#f2f5f9!important;color:#627086!important;font-size:14px!important;font-weight:800!important;line-height:1.35!important;padding:10px 12px!important;box-shadow:none!important}.lc-tab.lc-active{border-color:#2f7ce5!important;background:#2f7ce5!important;color:#fff!important}
.lc-field{display:grid!important;grid-template-columns:minmax(120px,.7fr) minmax(0,1.3fr)!important;align-items:center!important;gap:16px!important;padding:12px 14px!important;margin:0 0 10px!important;border:1px solid #dce6f1!important;border-radius:13px!important;background:#f7faff!important}.lc-field input:not([type=range]){min-height:44px!important;border:1px solid #cbd8e8!important;border-radius:10px!important;background:#fff!important;color:#0a2247!important;font-size:20px!important;font-weight:800!important}.lc-field input[type=range]{accent-color:#2f7ce5!important}
.lc-answer{border:1px solid #cfe0f3!important;border-radius:15px!important;background:#f7faff!important;box-shadow:none!important;overflow:hidden!important}.lc-breakdown{border:1px solid #d7e2ef!important;border-radius:15px!important;background:#fff!important;box-shadow:0 10px 28px rgba(10,34,71,.08)!important;overflow:hidden!important}
#lc-bars{margin:20px 0 8px;padding:20px 20px 16px;border:1px solid #d7e2ef;border-radius:16px;background:#fff;box-shadow:0 10px 30px rgba(10,34,71,.07)}.lc-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:14px}.lc-title{margin:0;color:#0a2247;font-size:18px;font-weight:900}.lc-note{margin:5px 0 0;color:#66758a;font-size:13px;line-height:1.55}.lc-legend{display:flex;flex-wrap:wrap;gap:12px 18px;color:#40516a;font-size:13px;font-weight:700}.lc-key{display:inline-flex;align-items:center;gap:7px;white-space:nowrap}.lc-swatch{width:13px;height:13px;border-radius:3px}.lc-p{background:#b9dcfb}.lc-g{background:#276ec5}
.lc-scroll{overflow-x:auto;overflow-y:hidden;padding:8px 2px 2px;scrollbar-width:thin}.lc-stage{position:relative;min-height:344px;padding:0 8px 38px;border-bottom:1px solid #dce6f1}.lc-columns{height:300px;display:flex;align-items:stretch;gap:8px;min-width:100%}.lc-col{flex:1 0 22px;min-width:22px;max-width:42px;position:relative;display:flex;flex-direction:column;justify-content:flex-end}.lc-bar{height:300px;padding:0;border:0;background:transparent;display:flex;flex-direction:column;justify-content:flex-end;cursor:pointer;outline:none}.lc-stack{width:100%;min-height:2px;display:flex;flex-direction:column;justify-content:flex-end;border-radius:5px 5px 2px 2px;overflow:hidden;transition:.15s}.lc-bar:hover .lc-stack,.lc-bar:focus-visible .lc-stack,.lc-bar.lc-selected .lc-stack{filter:brightness(.96);box-shadow:0 0 0 3px rgba(47,124,229,.14)}.lc-gain{background:#276ec5}.lc-principal{background:#b9dcfb;min-height:1px}.lc-label{position:absolute;top:306px;left:50%;transform:translateX(-50%);font-size:11px;font-weight:800;color:#55708f;white-space:nowrap}.lc-tip{position:absolute;z-index:4;left:12px;top:8px;min-width:190px;padding:11px 13px;border:1px solid #cddbed;border-radius:12px;background:rgba(255,255,255,.98);box-shadow:0 12px 30px rgba(10,34,71,.14);pointer-events:none}.lc-period{font-size:12px;font-weight:900;color:#2f7ce5;margin-bottom:6px}.lc-tiprow{display:flex;justify-content:space-between;gap:18px;font-size:12px;color:#52637b;line-height:1.75}.lc-tiprow strong{color:#0a2247;font-size:13px}.lc-footer{display:flex;justify-content:flex-end;margin-top:12px;color:#718097;font-size:11px;line-height:1.55}
@media(max-width:820px){main{padding:12px 12px 40px!important}.lc-tabs{grid-template-columns:repeat(2,minmax(0,1fr))!important}.lc-field{grid-template-columns:1fr!important;gap:7px!important}.lc-head{display:block}.lc-legend{margin-top:10px}#lc-bars{padding:16px 12px 12px}}
`;doc.head.appendChild(s)}
function inputFor(doc,label){const r=field(doc,label,true);return r?[...r.querySelectorAll('input')].find(i=>i.type!=='range'&&visible(i))||null:null}
const num=v=>{const n=Number(String(v||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const val=(doc,l)=>{const i=inputFor(doc,l);return i?num(i.value):0};
function mode(doc){const t=!!inputFor(doc,'目標額'),m=!!inputFor(doc,'毎月積立額'),y=!!inputFor(doc,'積立期間'),r=!!inputFor(doc,'利回り（年率）')||!!inputFor(doc,'利回り');if(!t&&m&&y&&r)return 0;if(t&&m&&!y&&r)return 1;if(t&&!m&&y&&r)return 2;if(t&&m&&y&&!r)return 3;return 0}
function answer(doc){const phrases=['入力条件で積立した場合','目標金額を達成するには'];const e=[...doc.querySelectorAll('div,p,span')].filter(x=>!x.closest('#lc-bars')&&visible(x)&&phrases.some(p=>norm(x.textContent).includes(norm(p)))).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!e)return null;let n=e;while(n&&n!==doc.body){if(/[0-9][0-9,]*(?:\.[0-9]+)?\s*(?:円|万円|%|年)/.test(n.innerText||''))return n;n=n.parentElement}return e.parentElement}
function near(doc,label,suffix){const e=exact(doc,label);if(!e)return 0;let n=e.parentElement;for(let d=0;n&&d<5;d++,n=n.parentElement){if(n.closest('#lc-bars'))continue;const m=(n.innerText||'').match(new RegExp('([0-9][0-9,]*(?:\\.[0-9]+)?)\\s*'+suffix));if(m)return num(m[1])}return 0}
function decorate(doc){const matches=['将来いくらになるか','積立期間を計算する','毎月積立額を計算する','利回りを計算する'];const tabs=[...doc.querySelectorAll('button')].filter(b=>visible(b)&&matches.some(x=>norm(b.textContent).includes(norm(x))));if(tabs.length>=4){const c=common(tabs);if(c)c.classList.add('lc-tabs');const active=mode(doc);tabs.forEach((b,i)=>{b.classList.add('lc-tab');b.classList.toggle('lc-active',i===active)})}['目標額','毎月積立額','積立期間','利回り（年率）','利回り'].forEach(l=>{const r=field(doc,l,true);if(r)r.classList.add('lc-field')});const a=answer(doc);if(a)a.classList.add('lc-answer');const e=exact(doc,'積立元本＋増えた額');if(e){let n=e;while(n&&n!==doc.body){const t=n.innerText||'';if(t.includes('積立元本')&&t.includes('増えた額')&&/[0-9,]+\s*円/.test(t)){n.classList.add('lc-breakdown');break}n=n.parentElement}}}
function state(doc){const md=mode(doc);let months=Math.max(1,Math.round(val(doc,'積立期間')*12)),monthly=val(doc,'毎月積立額')*10000,rate=val(doc,'利回り（年率）')||val(doc,'利回り');const a=answer(doc),txt=a?a.innerText:(doc.body.innerText||'');if(md===1){const m=txt.match(/(\d+)\s*年(?:\s*(\d+)\s*[ヶかケ]?月)?/);if(m)months=Math.max(1,+m[1]*12+(+m[2]||0))}if(md===3){const m=txt.match(/([0-9]+(?:\.[0-9]+)?)\s*%/);if(m)rate=+m[1]}let principal=near(doc,'積立元本','円'),gain=near(doc,'増えた額','円'),total=near(doc,'積立元本＋増えた額','円');if(md===2&&principal>0)monthly=principal/months;if(principal<=0)principal=Math.max(0,monthly*months);if(total<=0)total=principal+Math.max(0,gain);if(gain<=0&&total>=principal)gain=total-principal;return{md,months,monthly,rate,principal,gain,total}}
function fv(monthly,annual,months){if(monthly<=0||months<=0)return 0;const r=Math.pow(1+Math.max(-.999,annual/100),1/12)-1;return Math.abs(r)<1e-10?monthly*months:monthly*(Math.pow(1+r,months)-1)/r}
function points(s){const ms=[];for(let m=12;m<=s.months;m+=12)ms.push(m);if(!ms.length||ms[ms.length-1]!==s.months)ms.push(s.months);const approx=Math.max(0,fv(s.monthly,s.rate,s.months)-s.monthly*s.months),scale=approx>0?s.gain/approx:0;return ms.map(m=>{if(m===s.months)return{m,principal:s.principal,gain:s.gain,total:s.total};const principal=Math.min(s.principal,s.monthly*m),gain=Math.max(0,fv(s.monthly,s.rate,m)-s.monthly*m)*scale;return{m,principal,gain,total:principal+gain}})}
const yen=v=>Math.round(v||0).toLocaleString('ja-JP')+'円';
const period=m=>{const y=Math.floor(m/12),r=m%12;return y&&r?`${y}年${r}か月`:y?`${y}年目`:`${r}か月`};
function chartHost(doc){const old=doc.querySelector('[data-lc-old-chart="1"]');if(old&&old.isConnected)return old;const list=[...doc.querySelectorAll('svg,canvas')].filter(visible).map(e=>({e,a:e.getBoundingClientRect().width*e.getBoundingClientRect().height})).filter(x=>x.a>50000).sort((a,b)=>b.a-a.a);if(!list.length)return null;return list[0].e.closest('.recharts-responsive-container')||list[0].e.parentElement}
function tooltip(mount,p,b){const t=mount.querySelector('.lc-tip');if(!t)return;t.innerHTML=`<div class="lc-period">${period(p.m)}</div><div class="lc-tiprow"><span>積立元本</span><strong>${yen(p.principal)}</strong></div><div class="lc-tiprow"><span>運用で増えた額</span><strong>${yen(p.gain)}</strong></div><div class="lc-tiprow"><span>合計</span><strong>${yen(p.total)}</strong></div>`;mount.querySelectorAll('.lc-bar').forEach(x=>x.classList.remove('lc-selected'));b.classList.add('lc-selected')}
function draw(doc){const host=chartHost(doc);if(!host)return;const s=state(doc);if(!s.months||!s.total)return;const data=points(s);if(!data.length)return;const max=Math.max(...data.map(p=>p.total),1);let mount=doc.getElementById('lc-bars');if(!mount){mount=doc.createElement('section');mount.id='lc-bars';host.parentElement.insertBefore(mount,host)}host.dataset.lcOldChart='1';host.style.display='none';const marks=new Set([0,Math.floor((data.length-1)/2),data.length-1]),width=Math.max(620,data.length*32);mount.innerHTML=`<div class="lc-head"><div><h3 class="lc-title">積立元本と運用成果の推移</h3><p class="lc-note">棒全体が金融資産額です。元本と、運用で増えた金額を分けて表示します。</p></div><div class="lc-legend"><span class="lc-key"><i class="lc-swatch lc-p"></i>積立元本</span><span class="lc-key"><i class="lc-swatch lc-g"></i>運用で増えた額</span></div></div><div class="lc-scroll"><div class="lc-stage" style="min-width:${width}px"><div class="lc-tip"></div><div class="lc-columns"></div></div></div><div class="lc-footer">各棒を選択すると、その時点の内訳を確認できます。表示額はシミュレーション結果に合わせた概算推移です。</div>`;const cols=mount.querySelector('.lc-columns');data.forEach((p,i)=>{const h=Math.max(2,Math.round(p.total/max*270)),ph=Math.max(1,Math.round(p.principal/p.total*h)),gh=Math.max(0,h-ph),col=doc.createElement('div'),b=doc.createElement('button');col.className='lc-col';b.type='button';b.className='lc-bar'+(i===data.length-1?' lc-selected':'');b.setAttribute('aria-label',`${period(p.m)}、積立元本${yen(p.principal)}、運用で増えた額${yen(p.gain)}、合計${yen(p.total)}`);b.innerHTML=`<span class="lc-stack" style="height:${h}px"><span class="lc-gain" style="height:${gh}px"></span><span class="lc-principal" style="height:${ph}px"></span></span>`;if(marks.has(i)){const l=doc.createElement('span');l.className='lc-label';l.textContent=period(p.m);col.appendChild(l)}['mouseenter','focus','click'].forEach(ev=>b.addEventListener(ev,()=>tooltip(mount,p,b)));col.appendChild(b);cols.appendChild(col)});const bs=mount.querySelectorAll('.lc-bar');if(bs.length)tooltip(mount,data[data.length-1],bs[bs.length-1])}
function prepare(f){let tries=0,timer=null,busy=false;const schedule=(d=100)=>{clearTimeout(timer);timer=setTimeout(()=>{if(busy)return;busy=true;try{const doc=f.contentDocument;assetCss(doc);decorate(doc);draw(doc)}catch(e){console.error('asset enhancement',e)}finally{busy=false}},d)};const start=()=>{tries++;try{const doc=f.contentDocument;if(!doc)return;const b=[...doc.querySelectorAll('button')].find(x=>norm(x.textContent)===norm(ASSET));if(b){b.click();assetCss(doc);doc.documentElement.style.background='#fff';doc.addEventListener('input',()=>schedule(80),true);doc.addEventListener('change',()=>schedule(80),true);doc.addEventListener('click',()=>schedule(140),true);new MutationObserver(ms=>{if(ms.some(m=>!m.target.closest?.('#lc-bars')&&[...m.addedNodes].some(n=>n.nodeType===1)))schedule(110)}).observe(doc.body,{childList:true,subtree:true});schedule(260);return}}catch(e){console.error('asset bridge',e)}if(tries<60)setTimeout(start,150)};start()}
function open(button){activeButton=button;if(!overlay){overlay=document.createElement('div');overlay.id='lc-original-asset-overlay';Object.assign(overlay.style,{position:'fixed',left:'0',right:'0',bottom:'0',zIndex:'45',background:'#f2f6fb',padding:'10px',boxSizing:'border-box',overflow:'hidden'});frame=document.createElement('iframe');frame.title='資産運用シミュレーション';frame.src=LEGACY;Object.assign(frame.style,{width:'100%',height:'100%',border:'0',borderRadius:'16px',background:'#fff',boxShadow:'0 12px 36px rgba(10,34,71,.14)'});overlay.appendChild(frame);document.body.appendChild(overlay);frame.addEventListener('load',()=>prepare(frame))}overlay.style.display='block';positionOverlay()}
function wire(){document.querySelectorAll('button').forEach(b=>{if(b.dataset.lcAssetBridge)return;const t=norm(b.textContent);if(t===norm(ASSET)){b.dataset.lcAssetBridge='asset';b.addEventListener('click',()=>setTimeout(()=>open(b),30),true)}else if(['生活費逆算','住宅ローン','住宅ローン控除'].some(x=>t===norm(x))){b.dataset.lcAssetBridge='other';b.addEventListener('click',closeOverlay,true)}})}
addMainCss();const refresh=()=>{wire();improveDetails()};new MutationObserver(refresh).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('resize',positionOverlay);refresh();
})();
